### ISSUE TITLE
Calling stack trace

### ISSUE THREAD

**Issue by veelenga** [slvnperron/NUnit-GroupAssert#1]
@slvnperron Hello. Thanks for sharing your implementation. 

I have a little question. To find a source caller we have file path, method name and line number. As usual it's not enough. What about full source stack trace ?

**Comment by veelenga** [comment]
Ok, I have added stack trace info.
Sample:

``` C#
    class Sample
    {
        [SetUp]
        public void setUp()
        {
            AssertGroup.Clear();
        }

        [TearDown]
        public void tearDown()
        {
            AssertGroup.Verify();
        }

        [Test]
        public void sample()
        {
            inner_method();
        }

        public void inner_method()
        {
            inner_inner_method();
        }

        public void inner_inner_method()
        {
            AssertGroup.assertTrue(false, "This is fail");
        }
    }
```

And result looks like:

```
Test 'TestProject.Sample.sample' failed: TearDown : Test failed because one or more assertions failed: 
1)  This is fail
      Expected: True
      But was:  False
   at TestProject.Sample.inner_inner_method() in D:\TestProject\src\Sample.cs:line 36
   at TestCommons.Framework.Sample.inner_method() in D:\TestProject\src\Sample.cs:line 31
   at TestCommons.Framework.Sample.sample() in D:\TestProject\src\Sample.cs:line 26
```

Could be interesting for you?

**Comment by slvnperron** [comment]
Hi @veelenga,
thanks for reaching me. That is great to have the full stack trace, could you make a pull request please?
Thanks

**Comment by veelenga** [comment]
Ok. Coming soon

**Comment by slvnperron** [comment]
Thanks
